### ISSUE TITLE
New entity synthesis for RF Scanner devices

### ISSUE THREAD

**Issue by batbore** [newrelic-experimental/entity-synthesis-definitions#135]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
Opening enhancement request to add support for RF Scanner devices. 
[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution
Create RF Scanner entity. The required metrics are generated after receiving and parsing a scanner generated file in JSON format and ingesting via the Events API to create two custom event types. 

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by IreneMLC** [comment]
Closing this issue, since the entity type has already been added. Thanks for the contribution!
