### ISSUE TITLE
Adding support for Prometheus Redis

### ISSUE THREAD

**Issue by kidk** [newrelic-experimental/entity-synthesis-definitions#6]
I have customer using Prometheus heavily for Redis instances in their Kubernetes cluster. 

I tried creating the config file for this specific case, but I tried to stay away from Kubernetes specifics so I expect this to also work for Redis outside of Kubernetes.

ref: https://github.com/newrelic-experimental/entity-synthesis-definitions/pull/5

**Comment by IreneMLC** [comment]
PR merged, closing this issue.
